In [7]:
import pandas as pd
import csv

In [8]:
# Read the CSV file
Library_data = pd.read_csv("data/Library_Usage.csv")

/tmp/ipykernel_60281/825488449.py:2: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  Library_data = pd.read_csv("data/Library_Usage.csv")

In [9]:
df_library = pd.DataFrame(Library_data)

In [10]:
df_library

,Patron Type Definition,Total Checkouts,Total Renewals,Age Range,Home Library Definition,Circulation Active Month,Circulation Active Year,Notice Preference Definition,Provided Email Address,Year Patron Registered,Within San Francisco County
0,Senior,5,0,75 years and over,Main,Nov,2022,Email,True,2015,False
1,Adult,0,0,45 to 54 years,Main,Jul,2023,Email,True,2019,False
2,Adult,0,0,55 to 59 years,Western Addition,Mar,2024,Email,True,2022,False
3,Welcome,1,1,20 to 24 years,Richmond,Aug,2022,Email,True,2022,False
4,Senior,0,0,65 to 74 years,Sunset,Mar,2024,Print,False,2023,False
...,...,...,...,...,...,...,...,...,...,...,...
450354,Digital Access Card,0,0,35 to 44 years,Ingleside,Null,Null,Email,False,2023,Null
450355,Digital Access Card,0,0,45 to 54 years,Ingleside,Aug,2022,Print,False,2022,Null
450356,Digital Access Card,0,0,25 to 34 years,Ingleside,Aug,2022,Print,False,2022,Null
450357,Digital Access Card,0,0,35 to 44 years,Ingleside,Apr,2022,Print,False,2022,Null
450358,Digital Access Card,0,0,65 to 74 years,Bayview,Apr,2023,Email,False,2023,Null

In [11]:
df_library["Circulation Active Year"].unique()

array(['2022', '2023', '2024', '2021', 'Null', '2012', '2020', '2018',
       '2019', '2013', '2015', '2017', '2016', '2011', '2009', '2014',
       '2010', '2006', '2007', '2008', '2004', '2005'], dtype=object)

In [13]:
# 1. Wie viele Merkmale besitzt der Datensatz? Die Merkmale entsprechen den Spalten
len(df_library.columns)

11

In [14]:
# 2.Wie groÃŸ ist die StichprobengrÃ¶ÃŸe des Datensatzes?
len(df_library)

450359

In [15]:
df_library['Year Patron Registered'].value_counts(normalize=True)

Year Patron Registered
2023    0.132654
2022    0.115015
2003    0.088927
2021    0.072678
2019    0.072502
2020    0.065870
2017    0.064515
2018    0.062939
2016    0.048117
2015    0.043767
2014    0.033917
2013    0.028750
2012    0.027600
2011    0.026841
2009    0.024580
2010    0.024363
2008    0.021705
2007    0.014033
2006    0.011302
2005    0.010263
2004    0.009661
Name: proportion, dtype: float64

In [16]:
# 8. EnthÃ¤lt der Datensatz fehlende Werte? Ja, z.B. 'Circulation Active Year'

In [17]:
df_library[df_library['Circulation Active Year'].isna()]

Empty DataFrame
Columns: [Patron Type Definition, Total Checkouts, Total Renewals, Age Range, Home Library Definition, Circulation Active Month, Circulation Active Year, Notice Preference Definition, Provided Email Address, Year Patron Registered, Within San Francisco County]
Index: []

In [18]:
row_filter = (df_library['Age Range'] == '20 to 24 years') 
df_library.loc[row_filter]

,Patron Type Definition,Total Checkouts,Total Renewals,Age Range,Home Library Definition,Circulation Active Month,Circulation Active Year,Notice Preference Definition,Provided Email Address,Year Patron Registered,Within San Francisco County
3,Welcome,1,1,20 to 24 years,Richmond,Aug,2022,Email,True,2022,False
6,Adult,0,0,20 to 24 years,Main,Feb,2024,Email,True,2023,False
308,Adult,0,0,20 to 24 years,Main,Feb,2024,Email,True,2022,False
323,Adult,62,1,20 to 24 years,Main,Aug,2023,Email,True,2015,False
338,Adult,0,0,20 to 24 years,Main,Oct,2023,Print,False,2023,False
...,...,...,...,...,...,...,...,...,...,...,...
450186,Adult,0,0,20 to 24 years,Ingleside,Null,Null,Email,True,2022,Null
450255,Teen,1,0,20 to 24 years,Richmond,Feb,2024,Email,False,2023,Null
450284,Digital Access Card,0,0,20 to 24 years,Main,Dec,2021,Print,False,2021,Null
450304,Digital Access Card,0,0,20 to 24 years,Potrero,Oct,2022,Email,False,2022,Null
450330,Digital Access Card,0,0,20 to 24 years,Glen Park,Apr,2022,Print,False,2022,Null

In [19]:
df_library['Patron Type Definition'].value_counts()

Patron Type Definition
Adult                  284671
Juvenile                57486
Senior                  49025
Teen                    41042
Welcome                  9412
Digital Access Card      4558
Teacher Card             3415
Retired Staff             211
Visitor                   184
At User Adult             126
Library By Mail           116
At User Senior             73
At User Welcome            14
At User Teen                8
Business                    7
At User Juvenile            6
Bibliocommons               5
Name: count, dtype: int64

In [20]:
df_library['Age Range'].value_counts()

Age Range
25 to 34 years       95278
35 to 44 years       85669
10 to 19 years       67758
45 to 54 years       49820
0 to 9 years         33180
65 to 74 years       32455
20 to 24 years       27145
75 years and over    20721
55 to 59 years       19735
60 to 64 years       18088
Null                   510
Name: count, dtype: int64

In [22]:
#Kreuztabellierung erstellen mit crosstab
#Infos zu margins und normalize hier: https://docs.kanaries.net/de/topics/Pandas/pandas-crosstab
pd.crosstab(
    df_library['Patron Type Definition'],
    df_library['Notice Preference Definition'],
    margins=True,
    normalize=1
)

Notice Preference Definition     Email      Null     Phone     Print       All
Patron Type Definition
Adult                         0.658182  0.272700  0.370230  0.444515  0.632098
At User Adult                 0.000259  0.000000  0.000410  0.001118  0.000280
At User Juvenile              0.000012  0.000302  0.000000  0.000000  0.000013
At User Senior                0.000127  0.000302  0.000536  0.000479  0.000162
At User Teen                  0.000020  0.000000  0.000000  0.000000  0.000018
At User Welcome               0.000032  0.000000  0.000032  0.000000  0.000031
Bibliocommons                 0.000002  0.000000  0.000095  0.000160  0.000011
Business                      0.000017  0.000000  0.000000  0.000000  0.000016
Digital Access Card           0.006874  0.306787  0.009713  0.067220  0.010121
Juvenile                      0.121162  0.247964  0.183664  0.203736  0.127645
Library By Mail               0.000242  0.000000  0.000410  0.000639  0.000258
Retired Staff                 0.000486  0.000000  0.000252  0.000639  0.000469
Senior                        0.100080  0.041629  0.217471  0.167811  0.108858
Teacher Card                  0.008055  0.002413  0.002870  0.003353  0.007583
Teen                          0.084210  0.049170  0.191170  0.058917  0.091132
Visitor                       0.000420  0.000905  0.000158  0.000639  0.000409
Welcome                       0.019818  0.077828  0.022990  0.050774  0.020899

In [23]:
pd.crosstab(
    df_library['Age Range'],
    df_library['Notice Preference Definition'],
    margins=True,
    normalize=1
)

Notice Preference Definition     Email      Null     Phone     Print       All
Age Range
0 to 9 years                  0.073520  0.149321  0.049827  0.164458  0.073675
10 to 19 years                0.137177  0.157164  0.330937  0.100271  0.150453
20 to 24 years                0.059999  0.056712  0.067802  0.041993  0.060274
25 to 34 years                0.222186  0.215083  0.084358  0.159668  0.211560
35 to 44 years                0.199476  0.195777  0.077326  0.154559  0.190224
45 to 54 years                0.114398  0.092006  0.066919  0.095162  0.110623
55 to 59 years                0.044212  0.032881  0.039767  0.044547  0.043821
60 to 64 years                0.039335  0.036501  0.049732  0.047741  0.040164
65 to 74 years                0.068416  0.042534  0.116682  0.100112  0.072065
75 years and over             0.040181  0.019910  0.115926  0.086540  0.046010
Null                          0.001098  0.002112  0.000725  0.004950  0.001132

In [24]:
pd.crosstab(
    df_library['Patron Type Definition'],
    df_library['Age Range'],
    margins=True,
    normalize=1
)

Age Range,0 to 9 years,10 to 19 years,20 to 24 years,25 to 34 years,35 to 44 years,45 to 54 years,55 to 59 years,60 to 64 years,65 to 74 years,75 years and over,Null,All
Patron Type Definition,,,,,,,,,,,,
Adult,0.002230,0.030048,0.943968,0.938811,0.945161,0.950662,0.953332,0.955440,0.087321,0.005405,0.223529,0.632098
At User Adult,0.000000,0.000015,0.000258,0.000136,0.000303,0.000542,0.001064,0.001272,0.000185,0.000048,0.001961,0.000280
At User Juvenile,0.000090,0.000044,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000013
At User Senior,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.001325,0.001448,0.000000,0.000162
At User Teen,0.000000,0.000118,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000018
At User Welcome,0.000000,0.000044,0.000037,0.000021,0.000047,0.000040,0.000000,0.000055,0.000000,0.000048,0.000000,0.000031
Bibliocommons,0.000000,0.000000,0.000000,0.000052,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000011
Business,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000048,0.011765,0.000016
Digital Access Card,0.000181,0.001638,0.010978,0.014746,0.016680,0.013589,0.009678,0.008735,0.005238,0.002992,0.100000,0.010121
Juvenile,0.994967,0.360725,0.000147,0.000063,0.000117,0.000060,0.000000,0.000000,0.000031,0.000048,0.011765,0.127645
Library By Mail,0.000000,0.000000,0.000074,0.000084,0.000105,0.000100,0.000253,0.000332,0.000739,0.002751,0.000000,0.000258
Retired Staff,0.000000,0.000000,0.000000,0.000010,0.000000,0.000000,0.000456,0.000719,0.002342,0.001834,0.145098,0.000469
Senior,0.000000,0.000000,0.000000,0.000000,0.000023,0.000080,0.000963,0.003594,0.884055,0.975966,0.039216,0.108858
Teacher Card,0.002049,0.000059,0.004163,0.008029,0.011078,0.013268,0.013631,0.009454,0.005053,0.001351,0.437255,0.007583
Teen,0.000090,0.605390,0.000295,0.000010,0.000012,0.000020,0.000000,0.000000,0.000000,0.000000,0.015686,0.091132
Visitor,0.000090,0.000074,0.000958,0.000546,0.000374,0.000422,0.000507,0.000719,0.000401,0.000434,0.000000,0.000409
Welcome,0.000301,0.001845,0.039123,0.037490,0.026100,0.021216,0.020117,0.019682,0.013311,0.007625,0.013725,0.020899