In [1]:
import pandas as pd

df = pd.read_csv(
    "data/Library_Usage.csv", 
    low_memory=False,
    na_values="Null"
)
pd.crosstab(
    df['Notice Preference Definition'],
    df['Age Range'],
    margins=True
)

Age Range,0 to 9 years,10 to 19 years,20 to 24 years,25 to 34 years,35 to 44 years,45 to 54 years,55 to 59 years,60 to 64 years,65 to 74 years,75 years and over,All
Notice Preference Definition,,,,,,,,,,,
Email,30075,56115,24544,90890,81600,46797,18086,16091,27987,16437,408622
Phone,1580,10494,2150,2675,2452,2122,1261,1577,3700,3676,31687
Print,1030,628,263,1000,968,596,279,299,627,542,6232
All,32685,67237,26957,94565,85020,49515,19626,17967,32314,20655,446541

In [2]:
#normalize=1 normalisiert die Spalten, heißt die Werte in der Spalte ergeben summiert 100%
#92 % der 0-9 Jährigen wählen email
pd.crosstab(
    df['Notice Preference Definition'],
    df['Age Range'],
    margins=True, normalize=1
)

Age Range,0 to 9 years,10 to 19 years,20 to 24 years,25 to 34 years,35 to 44 years,45 to 54 years,55 to 59 years,60 to 64 years,65 to 74 years,75 years and over,All
Notice Preference Definition,,,,,,,,,,,
Email,0.920147,0.834585,0.910487,0.961138,0.959774,0.945108,0.921533,0.895586,0.866095,0.795788,0.915083
Phone,0.048340,0.156075,0.079757,0.028287,0.028840,0.042856,0.064252,0.087772,0.114501,0.177971,0.070961
Print,0.031513,0.009340,0.009756,0.010575,0.011386,0.012037,0.014216,0.016642,0.019403,0.026241,0.013956

In [3]:
#normalize=0 normalisiert die Zeilen, heißt die komplette Zeile ergibt 100%
#von allen mailkunden befinden sich 22% in der 25-34 Jahre Klasse
pd.crosstab(
    df['Notice Preference Definition'],
    df['Age Range'],
    margins=True, normalize=0
)

Age Range,0 to 9 years,10 to 19 years,20 to 24 years,25 to 34 years,35 to 44 years,45 to 54 years,55 to 59 years,60 to 64 years,65 to 74 years,75 years and over
Notice Preference Definition,,,,,,,,,,
Email,0.073601,0.137327,0.060065,0.222431,0.199696,0.114524,0.044261,0.039379,0.068491,0.040225
Phone,0.049863,0.331177,0.067851,0.084419,0.077382,0.066968,0.039795,0.049768,0.116767,0.116010
Print,0.165276,0.100770,0.042202,0.160462,0.155327,0.095635,0.044769,0.047978,0.100610,0.086970
All,0.073196,0.150573,0.060368,0.211772,0.190397,0.110886,0.043951,0.040236,0.072365,0.046256

In [4]:

#Korrelation berechnen
df['Total Checkouts'].corr(df['Total Renewals'])

0.6421628513121922